title: "NUSSU commIT Championship"
theme: jekyll-theme-slate

header_pages:
  - Overview.md
  - ChallengeStatement.md
  - Submission.md

markdown: kramdown

repository: "nussucommit/commit-championship"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
